version: 2

models:
  - name: sales
    description: Compares the sales and product IDs together. Sales orders ID is not null.
    tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"
          
    columns:
      - name: orders_id
        description: Sales orders ID (not null).
        tests: 
          - not_null 

      - name: products_id
        description: Product ID (not null).
        tests: 
          - not_null

      - name: qty

      - name: turnover
        description: Sales turnover (not null).
        tests:
          - not_null

      - name: purchase_cost
        description: Purchase cost (not null).
        tests:
          - not_null

      - name: margin